# Generated by Django 4.0.3 on 2022-05-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=19)),
                ('rating', models.DecimalField(blank=True, decimal_places=10, max_digits=19)),
                ('review', models.IntegerField(blank=True)),
                ('img', models.ImageField(upload_to='images/hotels')),
                ('adress', models.CharField(max_length=200)),
                ('map_X', models.CharField(blank=True, max_length=200)),
                ('map_Y', models.CharField(blank=True, max_length=200)),
                ('Description', models.TextField(blank=True)),
                ('facilities', models.TextField(blank=True)),
            ],
        ),
    ]
