# Generated by Django 4.0.3 on 2022-05-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_alter_hotel_price_alter_hotel_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='review',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
