# Generated by Django 4.0.3 on 2022-05-30 13:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0004_alter_hotel_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
