# Generated by Django 4.0.3 on 2022-05-31 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_client_about_alter_client_profile_host'),
        ('HomePage', '0005_alter_hotel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.host'),
        ),
    ]
