# Generated by Django 4.0.3 on 2022-05-31 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_client_about_alter_client_profile_host'),
        ('HomePage', '0008_remove_hotel_price_rooms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('booking_id', models.CharField(default='null', max_length=100)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.client')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomePage.rooms')),
            ],
        ),
    ]
