# Generated by Django 4.0.3 on 2022-05-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0009_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=19, null=True),
        ),
    ]
