# Generated by Django 4.0.3 on 2022-05-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_supadmin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupAdmin',
            new_name='SuperAdmin',
        ),
    ]
