# Generated by Django 4.0.3 on 2022-05-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_supadmin_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Erreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('erreur_date', models.DateTimeField(auto_now_add=True)),
                ('erreur', models.TextField()),
            ],
        ),
    ]
