# Generated by Django 4.0.3 on 2022-05-31 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_client_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='about',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile',
            field=models.ImageField(null=True, upload_to='images/clients'),
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(upload_to='images/hosts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
